[package]
name = "slintgen"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.20.10"
tree-sitter-slint = {git = "https://github.com/slint-ui/tree-sitter-slint"}

[build-dependencies]
cc="*"

